name: ActionOnInteract
version: '${project.version}'
main: com.spaceniklas.actiononinteract.Actiononinteract
api-version: 1.16
authors: [ SpaceNiklas ]
description: Executes an action on interact!
website: www.spaceniklas.com
